
CREATE USER autoparts IDENTIFIED BY autoparts123;
GRANT CONNECT, RESOURCE TO autoparts;
GRANT CREATE SESSION TO autoparts;
GRANT CREATE TABLE TO autoparts;

CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR2(100),
    password VARCHAR2(100)
);

CREATE TABLE products (
    product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR2(100),
    price NUMBER(10,2)
);

INSERT INTO products(product_name, price) VALUES ('Brake Pads', 2500);
INSERT INTO products(product_name, price) VALUES ('Battery', 4500);
INSERT INTO products(product_name, price) VALUES ('Tires', 6000);
